// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package punycode

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("punycode", "library.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  return nil, nil
})

