// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package keychain

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("keychain", "keychain.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  return nil, nil
})

