// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package fs

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("fs", "/Users/tim/src/grexie/solid/pkg/runtime/fs/direntry.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  return nil, nil
})

func (e *dirEntry) V8FuncIsDirectory(in isolates.FunctionArgs) (*isolates.Value, error) {
  result := e.IsDirectory()
  return in.Context.Create(in.ExecutionContext, result)
}

func (e *dirEntry) V8FuncIsFile(in isolates.FunctionArgs) (*isolates.Value, error) {
  result := e.IsFile()
  return in.Context.Create(in.ExecutionContext, result)
}

func (e *dirEntry) V8GetName(in isolates.GetterArgs) (*isolates.Value, error) {
  result := e.Name()
  return in.Context.Create(in.ExecutionContext, result)
}