// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package fs

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("fs", "fd.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  return nil, nil
})

