// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package tls

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("tls", "library.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  return nil, nil
})

