// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package worker_threads

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("worker_threads", "worker_threads.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  return nil, nil
})

