//js:package native/macos/io-kit
package io_kit

//go:generate go run github.com/grexie/isolates/codegen

/*
struct IOKit.SBCModePageFormatDevice
*/

type SBCModePageFormatDevice struct {
  Header ModePageFormatHeader `v8:"header"`
  TRACKSPERZONE uint16 `v8:"tRACKSPERZONE"`
  ALTERNATESECTORSPERZONE uint16 `v8:"aLTERNATESECTORSPERZONE"`
  ALTERNATETRACKSPERZONE uint16 `v8:"aLTERNATETRACKSPERZONE"`
  ALTERNATETRACKSPERLOGICALUNIT uint16 `v8:"aLTERNATETRACKSPERLOGICALUNIT"`
  SECTORSPERTRACK uint16 `v8:"sECTORSPERTRACK"`
  DATABYTESPERPHYSICALSECTOR uint16 `v8:"dATABYTESPERPHYSICALSECTOR"`
  INTERLEAVE uint16 `v8:"iNTERLEAVE"`
  TRACKSKEWFACTOR uint16 `v8:"tRACKSKEWFACTOR"`
  CYLINDERSKEWFACTOR uint16 `v8:"cYLINDERSKEWFACTOR"`
  SSECHSECRMBSURF byte `v8:"sSECHSECRMBSURF"`
  RESERVED [3]byte `v8:"rESERVED"`
}
