//js:package native/macos/io-kit
package io_kit

//go:generate go run github.com/grexie/isolates/codegen

/*
struct IOKit.SBCModePageFlexibleDisk
*/

type SBCModePageFlexibleDisk struct {
  Header ModePageFormatHeader `v8:"header"`
  TRANSFERRATE uint16 `v8:"tRANSFERRATE"`
  NUMBEROFHEADS byte `v8:"nUMBEROFHEADS"`
  SECTORSPERTRACK byte `v8:"sECTORSPERTRACK"`
  DATABYTESPERSECTOR uint16 `v8:"dATABYTESPERSECTOR"`
  NUMBEROFCYLINDERS uint16 `v8:"nUMBEROFCYLINDERS"`
  STARTINGCYLINDERWRITEPRECOMPENSATION uint16 `v8:"sTARTINGCYLINDERWRITEPRECOMPENSATION"`
  STARTINGCYLINDERREDUCEDWRITECURRENT uint16 `v8:"sTARTINGCYLINDERREDUCEDWRITECURRENT"`
  DEVICESTEPRATE uint16 `v8:"dEVICESTEPRATE"`
  DEVICESTEPPULSEWIDTH byte `v8:"dEVICESTEPPULSEWIDTH"`
  HEADSETTLEDELAY uint16 `v8:"hEADSETTLEDELAY"`
  MOTORONDELAY byte `v8:"mOTORONDELAY"`
  MOTOROFFDELAY byte `v8:"mOTOROFFDELAY"`
  TRDYSSNMO byte `v8:"tRDYSSNMO"`
  SPC byte `v8:"sPC"`
  WRITECOMPENSATION byte `v8:"wRITECOMPENSATION"`
  HEADLOADDELAY byte `v8:"hEADLOADDELAY"`
  HEADUNLOADDELAY byte `v8:"hEADUNLOADDELAY"`
  PIN34PIN2 byte `v8:"pIN34PIN2"`
  PIN4PIN1 byte `v8:"pIN4PIN1"`
  MEDIUMROTATIONRATE uint16 `v8:"mEDIUMROTATIONRATE"`
  RESERVED [2]byte `v8:"rESERVED"`
}
