//js:package native/macos/io-kit
package io_kit

//go:generate go run github.com/grexie/isolates/codegen

/*
struct IOKit.SCSI_Sense_Data
*/

type SCSISenseData struct {
  VALIDRESPONSECODE byte `v8:"vALIDRESPONSECODE"`
  SEGMENTNUMBER byte `v8:"sEGMENTNUMBER"`
  SENSEKEY byte `v8:"sENSEKEY"`
  INFORMATION1 byte `v8:"iNFORMATION1"`
  INFORMATION2 byte `v8:"iNFORMATION2"`
  INFORMATION3 byte `v8:"iNFORMATION3"`
  INFORMATION4 byte `v8:"iNFORMATION4"`
  ADDITIONALSENSELENGTH byte `v8:"aDDITIONALSENSELENGTH"`
  COMMANDSPECIFICINFORMATION1 byte `v8:"cOMMANDSPECIFICINFORMATION1"`
  COMMANDSPECIFICINFORMATION2 byte `v8:"cOMMANDSPECIFICINFORMATION2"`
  COMMANDSPECIFICINFORMATION3 byte `v8:"cOMMANDSPECIFICINFORMATION3"`
  COMMANDSPECIFICINFORMATION4 byte `v8:"cOMMANDSPECIFICINFORMATION4"`
  ADDITIONALSENSECODE byte `v8:"aDDITIONALSENSECODE"`
  ADDITIONALSENSECODEQUALIFIER byte `v8:"aDDITIONALSENSECODEQUALIFIER"`
  FIELDREPLACEABLEUNITCODE byte `v8:"fIELDREPLACEABLEUNITCODE"`
  SKSVSENSEKEYSPECIFICMSB byte `v8:"sKSVSENSEKEYSPECIFICMSB"`
  SENSEKEYSPECIFICMID byte `v8:"sENSEKEYSPECIFICMID"`
  SENSEKEYSPECIFICLSB byte `v8:"sENSEKEYSPECIFICLSB"`
}
