//js:package native/macos/io-kit
package io_kit

//go:generate go run github.com/grexie/isolates/codegen

/*
struct IOKit.SCSICmd_INQUIRY_PageB0_Data
*/

type SCSICmdINQUIRYPageB0Data struct {
  PERIPHERALDEVICETYPE byte `v8:"pERIPHERALDEVICETYPE"`
  PAGECODE byte `v8:"pAGECODE"`
  PAGELENGTH uint16 `v8:"pAGELENGTH"`
  WSNZ byte `v8:"wSNZ"`
  MAXIMUMCOMPAREANDWRITELENGTH byte `v8:"mAXIMUMCOMPAREANDWRITELENGTH"`
  OPTIMALTRANSFERLENGTHGRANULARITY uint16 `v8:"oPTIMALTRANSFERLENGTHGRANULARITY"`
  MAXIMUMTRANSFERLENGTH uint `v8:"mAXIMUMTRANSFERLENGTH"`
  OPTIMALTRANSFERLENGTH uint `v8:"oPTIMALTRANSFERLENGTH"`
  MAXIMUMPREFETCHLENGTH uint `v8:"mAXIMUMPREFETCHLENGTH"`
  MAXIMUMUNMAPLBACOUNT uint `v8:"mAXIMUMUNMAPLBACOUNT"`
  MAXIMUMUNMAPBLOCKDESCRIPTORCOUNT uint `v8:"mAXIMUMUNMAPBLOCKDESCRIPTORCOUNT"`
  OPTIMALUNMAPGRANULARITY uint `v8:"oPTIMALUNMAPGRANULARITY"`
  UNMAPGRANULARITYALIGNMENT uint `v8:"uNMAPGRANULARITYALIGNMENT"`
  MAXIMUMWRITESAMELENGTH uint64 `v8:"mAXIMUMWRITESAMELENGTH"`
  MAXIMUMATOMICTRANSFERLENGTH uint `v8:"mAXIMUMATOMICTRANSFERLENGTH"`
  ATOMICALIGNMENT uint `v8:"aTOMICALIGNMENT"`
  ATOMICTRANSFERLENGTHGRANULARITY uint `v8:"aTOMICTRANSFERLENGTHGRANULARITY"`
  MAXIMUMATOMICTRANSFERLENGTHWITHATOMICBOUNDARY uint `v8:"mAXIMUMATOMICTRANSFERLENGTHWITHATOMICBOUNDARY"`
  MAXIMUMATOMICBOUNDARYSIZE uint `v8:"mAXIMUMATOMICBOUNDARYSIZE"`
}
