// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package stream

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("stream", "/Users/tim/src/grexie/solid/pkg/runtime/stream/transform.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  if constructor, err := in.Context.CreateWithName(in.ExecutionContext, "Transform", func (in isolates.FunctionArgs) (*TransformBase, error) {
    return NewTransform(in)
  }); err != nil {
    return nil, err
  } else if err := in.Args[1].Set(in.ExecutionContext, "Transform", constructor); err != nil {
    return nil, err
  }

  return nil, nil
})

