//js:package native/macos/open-gl
package open_gl

//go:generate go run github.com/grexie/isolates/codegen

/*
struct OpenGL.GLIFunctionDispatch
*/

type GLIFunctionDispatch struct {
  Accum func(...any) (any, error) `v8:"accum"`
  AlphaFunc func(...any) (any, error) `v8:"alphaFunc"`
  AreTexturesResident func(...any) (any, error) `v8:"areTexturesResident"`
  ArrayElement func(...any) (any, error) `v8:"arrayElement"`
  Begin func(...any) (any, error) `v8:"begin"`
  BindTexture func(...any) (any, error) `v8:"bindTexture"`
  Bitmap func(...any) (any, error) `v8:"bitmap"`
  BlendFunc func(...any) (any, error) `v8:"blendFunc"`
  CallList func(...any) (any, error) `v8:"callList"`
  CallLists func(...any) (any, error) `v8:"callLists"`
  Clear func(...any) (any, error) `v8:"clear"`
  ClearAccum func(...any) (any, error) `v8:"clearAccum"`
  ClearColor func(...any) (any, error) `v8:"clearColor"`
  ClearDepth func(...any) (any, error) `v8:"clearDepth"`
  ClearIndex func(...any) (any, error) `v8:"clearIndex"`
  ClearStencil func(...any) (any, error) `v8:"clearStencil"`
  ClipPlane func(...any) (any, error) `v8:"clipPlane"`
  Color3b func(...any) (any, error) `v8:"color3b"`
  Color3bv func(...any) (any, error) `v8:"color3bv"`
  Color3d func(...any) (any, error) `v8:"color3d"`
  Color3dv func(...any) (any, error) `v8:"color3dv"`
  Color3f func(...any) (any, error) `v8:"color3f"`
  Color3fv func(...any) (any, error) `v8:"color3fv"`
  Color3i func(...any) (any, error) `v8:"color3i"`
  Color3iv func(...any) (any, error) `v8:"color3iv"`
  Color3s func(...any) (any, error) `v8:"color3s"`
  Color3sv func(...any) (any, error) `v8:"color3sv"`
  Color3ub func(...any) (any, error) `v8:"color3ub"`
  Color3ubv func(...any) (any, error) `v8:"color3ubv"`
  Color3ui func(...any) (any, error) `v8:"color3ui"`
  Color3uiv func(...any) (any, error) `v8:"color3uiv"`
  Color3us func(...any) (any, error) `v8:"color3us"`
  Color3usv func(...any) (any, error) `v8:"color3usv"`
  Color4b func(...any) (any, error) `v8:"color4b"`
  Color4bv func(...any) (any, error) `v8:"color4bv"`
  Color4d func(...any) (any, error) `v8:"color4d"`
  Color4dv func(...any) (any, error) `v8:"color4dv"`
  Color4f func(...any) (any, error) `v8:"color4f"`
  Color4fv func(...any) (any, error) `v8:"color4fv"`
  Color4i func(...any) (any, error) `v8:"color4i"`
  Color4iv func(...any) (any, error) `v8:"color4iv"`
  Color4s func(...any) (any, error) `v8:"color4s"`
  Color4sv func(...any) (any, error) `v8:"color4sv"`
  Color4ub func(...any) (any, error) `v8:"color4ub"`
  Color4ubv func(...any) (any, error) `v8:"color4ubv"`
  Color4ui func(...any) (any, error) `v8:"color4ui"`
  Color4uiv func(...any) (any, error) `v8:"color4uiv"`
  Color4us func(...any) (any, error) `v8:"color4us"`
  Color4usv func(...any) (any, error) `v8:"color4usv"`
  ColorMask func(...any) (any, error) `v8:"colorMask"`
  ColorMaterial func(...any) (any, error) `v8:"colorMaterial"`
  ColorPointer func(...any) (any, error) `v8:"colorPointer"`
  CopyPixels func(...any) (any, error) `v8:"copyPixels"`
  CopyTexImage1D func(...any) (any, error) `v8:"copyTexImage1D"`
  CopyTexImage2D func(...any) (any, error) `v8:"copyTexImage2D"`
  CopyTexSubImage1D func(...any) (any, error) `v8:"copyTexSubImage1D"`
  CopyTexSubImage2D func(...any) (any, error) `v8:"copyTexSubImage2D"`
  CullFace func(...any) (any, error) `v8:"cullFace"`
  DeleteLists func(...any) (any, error) `v8:"deleteLists"`
  DeleteTextures func(...any) (any, error) `v8:"deleteTextures"`
  DepthFunc func(...any) (any, error) `v8:"depthFunc"`
  DepthMask func(...any) (any, error) `v8:"depthMask"`
  DepthRange func(...any) (any, error) `v8:"depthRange"`
  Disable func(...any) (any, error) `v8:"disable"`
  DisableClientState func(...any) (any, error) `v8:"disableClientState"`
  DrawArrays func(...any) (any, error) `v8:"drawArrays"`
  DrawBuffer func(...any) (any, error) `v8:"drawBuffer"`
  DrawElements func(...any) (any, error) `v8:"drawElements"`
  DrawPixels func(...any) (any, error) `v8:"drawPixels"`
  EdgeFlag func(...any) (any, error) `v8:"edgeFlag"`
  EdgeFlagPointer func(...any) (any, error) `v8:"edgeFlagPointer"`
  EdgeFlagv func(...any) (any, error) `v8:"edgeFlagv"`
  Enable func(...any) (any, error) `v8:"enable"`
  EnableClientState func(...any) (any, error) `v8:"enableClientState"`
  End func(...any) (any, error) `v8:"end"`
  EndList func(...any) (any, error) `v8:"endList"`
  EvalCoord1d func(...any) (any, error) `v8:"evalCoord1d"`
  EvalCoord1dv func(...any) (any, error) `v8:"evalCoord1dv"`
  EvalCoord1f func(...any) (any, error) `v8:"evalCoord1f"`
  EvalCoord1fv func(...any) (any, error) `v8:"evalCoord1fv"`
  EvalCoord2d func(...any) (any, error) `v8:"evalCoord2d"`
  EvalCoord2dv func(...any) (any, error) `v8:"evalCoord2dv"`
  EvalCoord2f func(...any) (any, error) `v8:"evalCoord2f"`
  EvalCoord2fv func(...any) (any, error) `v8:"evalCoord2fv"`
  EvalMesh1 func(...any) (any, error) `v8:"evalMesh1"`
  EvalMesh2 func(...any) (any, error) `v8:"evalMesh2"`
  EvalPoint1 func(...any) (any, error) `v8:"evalPoint1"`
  EvalPoint2 func(...any) (any, error) `v8:"evalPoint2"`
  FeedbackBuffer func(...any) (any, error) `v8:"feedbackBuffer"`
  Finish func(...any) (any, error) `v8:"finish"`
  Flush func(...any) (any, error) `v8:"flush"`
  Fogf func(...any) (any, error) `v8:"fogf"`
  Fogfv func(...any) (any, error) `v8:"fogfv"`
  Fogi func(...any) (any, error) `v8:"fogi"`
  Fogiv func(...any) (any, error) `v8:"fogiv"`
  FrontFace func(...any) (any, error) `v8:"frontFace"`
  Frustum func(...any) (any, error) `v8:"frustum"`
  GenLists func(...any) (any, error) `v8:"genLists"`
  GenTextures func(...any) (any, error) `v8:"genTextures"`
  GetBooleanv func(...any) (any, error) `v8:"getBooleanv"`
  GetClipPlane func(...any) (any, error) `v8:"getClipPlane"`
  GetDoublev func(...any) (any, error) `v8:"getDoublev"`
  GetError func(...any) (any, error) `v8:"getError"`
  GetFloatv func(...any) (any, error) `v8:"getFloatv"`
  GetIntegerv func(...any) (any, error) `v8:"getIntegerv"`
  GetLightfv func(...any) (any, error) `v8:"getLightfv"`
  GetLightiv func(...any) (any, error) `v8:"getLightiv"`
  GetMapdv func(...any) (any, error) `v8:"getMapdv"`
  GetMapfv func(...any) (any, error) `v8:"getMapfv"`
  GetMapiv func(...any) (any, error) `v8:"getMapiv"`
  GetMaterialfv func(...any) (any, error) `v8:"getMaterialfv"`
  GetMaterialiv func(...any) (any, error) `v8:"getMaterialiv"`
  GetPixelMapfv func(...any) (any, error) `v8:"getPixelMapfv"`
  GetPixelMapuiv func(...any) (any, error) `v8:"getPixelMapuiv"`
  GetPixelMapusv func(...any) (any, error) `v8:"getPixelMapusv"`
  GetPointerv func(...any) (any, error) `v8:"getPointerv"`
  GetPolygonStipple func(...any) (any, error) `v8:"getPolygonStipple"`
  GetString func(...any) (any, error) `v8:"getString"`
  GetTexEnvfv func(...any) (any, error) `v8:"getTexEnvfv"`
  GetTexEnviv func(...any) (any, error) `v8:"getTexEnviv"`
  GetTexGendv func(...any) (any, error) `v8:"getTexGendv"`
  GetTexGenfv func(...any) (any, error) `v8:"getTexGenfv"`
  GetTexGeniv func(...any) (any, error) `v8:"getTexGeniv"`
  GetTexImage func(...any) (any, error) `v8:"getTexImage"`
  GetTexLevelParameterfv func(...any) (any, error) `v8:"getTexLevelParameterfv"`
  GetTexLevelParameteriv func(...any) (any, error) `v8:"getTexLevelParameteriv"`
  GetTexParameterfv func(...any) (any, error) `v8:"getTexParameterfv"`
  GetTexParameteriv func(...any) (any, error) `v8:"getTexParameteriv"`
  Hint func(...any) (any, error) `v8:"hint"`
  IndexMask func(...any) (any, error) `v8:"indexMask"`
  IndexPointer func(...any) (any, error) `v8:"indexPointer"`
  Indexd func(...any) (any, error) `v8:"indexd"`
  Indexdv func(...any) (any, error) `v8:"indexdv"`
  Indexf func(...any) (any, error) `v8:"indexf"`
  Indexfv func(...any) (any, error) `v8:"indexfv"`
  Indexi func(...any) (any, error) `v8:"indexi"`
  Indexiv func(...any) (any, error) `v8:"indexiv"`
  Indexs func(...any) (any, error) `v8:"indexs"`
  Indexsv func(...any) (any, error) `v8:"indexsv"`
  Indexub func(...any) (any, error) `v8:"indexub"`
  Indexubv func(...any) (any, error) `v8:"indexubv"`
  InitNames func(...any) (any, error) `v8:"initNames"`
  InterleavedArrays func(...any) (any, error) `v8:"interleavedArrays"`
  IsEnabled func(...any) (any, error) `v8:"isEnabled"`
  IsList func(...any) (any, error) `v8:"isList"`
  IsTexture func(...any) (any, error) `v8:"isTexture"`
  LightModelf func(...any) (any, error) `v8:"lightModelf"`
  LightModelfv func(...any) (any, error) `v8:"lightModelfv"`
  LightModeli func(...any) (any, error) `v8:"lightModeli"`
  LightModeliv func(...any) (any, error) `v8:"lightModeliv"`
  Lightf func(...any) (any, error) `v8:"lightf"`
  Lightfv func(...any) (any, error) `v8:"lightfv"`
  Lighti func(...any) (any, error) `v8:"lighti"`
  Lightiv func(...any) (any, error) `v8:"lightiv"`
  LineStipple func(...any) (any, error) `v8:"lineStipple"`
  LineWidth func(...any) (any, error) `v8:"lineWidth"`
  ListBase func(...any) (any, error) `v8:"listBase"`
  LoadIdentity func(...any) (any, error) `v8:"loadIdentity"`
  LoadMatrixd func(...any) (any, error) `v8:"loadMatrixd"`
  LoadMatrixf func(...any) (any, error) `v8:"loadMatrixf"`
  LoadName func(...any) (any, error) `v8:"loadName"`
  LogicOp func(...any) (any, error) `v8:"logicOp"`
  Map1d func(...any) (any, error) `v8:"map1d"`
  Map1f func(...any) (any, error) `v8:"map1f"`
  Map2d func(...any) (any, error) `v8:"map2d"`
  Map2f func(...any) (any, error) `v8:"map2f"`
  MapGrid1d func(...any) (any, error) `v8:"mapGrid1d"`
  MapGrid1f func(...any) (any, error) `v8:"mapGrid1f"`
  MapGrid2d func(...any) (any, error) `v8:"mapGrid2d"`
  MapGrid2f func(...any) (any, error) `v8:"mapGrid2f"`
  Materialf func(...any) (any, error) `v8:"materialf"`
  Materialfv func(...any) (any, error) `v8:"materialfv"`
  Materiali func(...any) (any, error) `v8:"materiali"`
  Materialiv func(...any) (any, error) `v8:"materialiv"`
  MatrixMode func(...any) (any, error) `v8:"matrixMode"`
  MultMatrixd func(...any) (any, error) `v8:"multMatrixd"`
  MultMatrixf func(...any) (any, error) `v8:"multMatrixf"`
  NewList func(...any) (any, error) `v8:"newList"`
  Normal3b func(...any) (any, error) `v8:"normal3b"`
  Normal3bv func(...any) (any, error) `v8:"normal3bv"`
  Normal3d func(...any) (any, error) `v8:"normal3d"`
  Normal3dv func(...any) (any, error) `v8:"normal3dv"`
  Normal3f func(...any) (any, error) `v8:"normal3f"`
  Normal3fv func(...any) (any, error) `v8:"normal3fv"`
  Normal3i func(...any) (any, error) `v8:"normal3i"`
  Normal3iv func(...any) (any, error) `v8:"normal3iv"`
  Normal3s func(...any) (any, error) `v8:"normal3s"`
  Normal3sv func(...any) (any, error) `v8:"normal3sv"`
  NormalPointer func(...any) (any, error) `v8:"normalPointer"`
  Ortho func(...any) (any, error) `v8:"ortho"`
  PassThrough func(...any) (any, error) `v8:"passThrough"`
  PixelMapfv func(...any) (any, error) `v8:"pixelMapfv"`
  PixelMapuiv func(...any) (any, error) `v8:"pixelMapuiv"`
  PixelMapusv func(...any) (any, error) `v8:"pixelMapusv"`
  PixelStoref func(...any) (any, error) `v8:"pixelStoref"`
  PixelStorei func(...any) (any, error) `v8:"pixelStorei"`
  PixelTransferf func(...any) (any, error) `v8:"pixelTransferf"`
  PixelTransferi func(...any) (any, error) `v8:"pixelTransferi"`
  PixelZoom func(...any) (any, error) `v8:"pixelZoom"`
  PointSize func(...any) (any, error) `v8:"pointSize"`
  PolygonMode func(...any) (any, error) `v8:"polygonMode"`
  PolygonOffset func(...any) (any, error) `v8:"polygonOffset"`
  PolygonStipple func(...any) (any, error) `v8:"polygonStipple"`
  PopAttrib func(...any) (any, error) `v8:"popAttrib"`
  PopClientAttrib func(...any) (any, error) `v8:"popClientAttrib"`
  PopMatrix func(...any) (any, error) `v8:"popMatrix"`
  PopName func(...any) (any, error) `v8:"popName"`
  PrioritizeTextures func(...any) (any, error) `v8:"prioritizeTextures"`
  PushAttrib func(...any) (any, error) `v8:"pushAttrib"`
  PushClientAttrib func(...any) (any, error) `v8:"pushClientAttrib"`
  PushMatrix func(...any) (any, error) `v8:"pushMatrix"`
  PushName func(...any) (any, error) `v8:"pushName"`
  RasterPos2d func(...any) (any, error) `v8:"rasterPos2d"`
  RasterPos2dv func(...any) (any, error) `v8:"rasterPos2dv"`
  RasterPos2f func(...any) (any, error) `v8:"rasterPos2f"`
  RasterPos2fv func(...any) (any, error) `v8:"rasterPos2fv"`
  RasterPos2i func(...any) (any, error) `v8:"rasterPos2i"`
  RasterPos2iv func(...any) (any, error) `v8:"rasterPos2iv"`
  RasterPos2s func(...any) (any, error) `v8:"rasterPos2s"`
  RasterPos2sv func(...any) (any, error) `v8:"rasterPos2sv"`
  RasterPos3d func(...any) (any, error) `v8:"rasterPos3d"`
  RasterPos3dv func(...any) (any, error) `v8:"rasterPos3dv"`
  RasterPos3f func(...any) (any, error) `v8:"rasterPos3f"`
  RasterPos3fv func(...any) (any, error) `v8:"rasterPos3fv"`
  RasterPos3i func(...any) (any, error) `v8:"rasterPos3i"`
  RasterPos3iv func(...any) (any, error) `v8:"rasterPos3iv"`
  RasterPos3s func(...any) (any, error) `v8:"rasterPos3s"`
  RasterPos3sv func(...any) (any, error) `v8:"rasterPos3sv"`
  RasterPos4d func(...any) (any, error) `v8:"rasterPos4d"`
  RasterPos4dv func(...any) (any, error) `v8:"rasterPos4dv"`
  RasterPos4f func(...any) (any, error) `v8:"rasterPos4f"`
  RasterPos4fv func(...any) (any, error) `v8:"rasterPos4fv"`
  RasterPos4i func(...any) (any, error) `v8:"rasterPos4i"`
  RasterPos4iv func(...any) (any, error) `v8:"rasterPos4iv"`
  RasterPos4s func(...any) (any, error) `v8:"rasterPos4s"`
  RasterPos4sv func(...any) (any, error) `v8:"rasterPos4sv"`
  ReadBuffer func(...any) (any, error) `v8:"readBuffer"`
  ReadPixels func(...any) (any, error) `v8:"readPixels"`
  Rectd func(...any) (any, error) `v8:"rectd"`
  Rectdv func(...any) (any, error) `v8:"rectdv"`
  Rectf func(...any) (any, error) `v8:"rectf"`
  Rectfv func(...any) (any, error) `v8:"rectfv"`
  Recti func(...any) (any, error) `v8:"recti"`
  Rectiv func(...any) (any, error) `v8:"rectiv"`
  Rects func(...any) (any, error) `v8:"rects"`
  Rectsv func(...any) (any, error) `v8:"rectsv"`
  RenderMode func(...any) (any, error) `v8:"renderMode"`
  Rotated func(...any) (any, error) `v8:"rotated"`
  Rotatef func(...any) (any, error) `v8:"rotatef"`
  Scaled func(...any) (any, error) `v8:"scaled"`
  Scalef func(...any) (any, error) `v8:"scalef"`
  Scissor func(...any) (any, error) `v8:"scissor"`
  SelectBuffer func(...any) (any, error) `v8:"selectBuffer"`
  ShadeModel func(...any) (any, error) `v8:"shadeModel"`
  StencilFunc func(...any) (any, error) `v8:"stencilFunc"`
  StencilMask func(...any) (any, error) `v8:"stencilMask"`
  StencilOp func(...any) (any, error) `v8:"stencilOp"`
  TexCoord1d func(...any) (any, error) `v8:"texCoord1d"`
  TexCoord1dv func(...any) (any, error) `v8:"texCoord1dv"`
  TexCoord1f func(...any) (any, error) `v8:"texCoord1f"`
  TexCoord1fv func(...any) (any, error) `v8:"texCoord1fv"`
  TexCoord1i func(...any) (any, error) `v8:"texCoord1i"`
  TexCoord1iv func(...any) (any, error) `v8:"texCoord1iv"`
  TexCoord1s func(...any) (any, error) `v8:"texCoord1s"`
  TexCoord1sv func(...any) (any, error) `v8:"texCoord1sv"`
  TexCoord2d func(...any) (any, error) `v8:"texCoord2d"`
  TexCoord2dv func(...any) (any, error) `v8:"texCoord2dv"`
  TexCoord2f func(...any) (any, error) `v8:"texCoord2f"`
  TexCoord2fv func(...any) (any, error) `v8:"texCoord2fv"`
  TexCoord2i func(...any) (any, error) `v8:"texCoord2i"`
  TexCoord2iv func(...any) (any, error) `v8:"texCoord2iv"`
  TexCoord2s func(...any) (any, error) `v8:"texCoord2s"`
  TexCoord2sv func(...any) (any, error) `v8:"texCoord2sv"`
  TexCoord3d func(...any) (any, error) `v8:"texCoord3d"`
  TexCoord3dv func(...any) (any, error) `v8:"texCoord3dv"`
  TexCoord3f func(...any) (any, error) `v8:"texCoord3f"`
  TexCoord3fv func(...any) (any, error) `v8:"texCoord3fv"`
  TexCoord3i func(...any) (any, error) `v8:"texCoord3i"`
  TexCoord3iv func(...any) (any, error) `v8:"texCoord3iv"`
  TexCoord3s func(...any) (any, error) `v8:"texCoord3s"`
  TexCoord3sv func(...any) (any, error) `v8:"texCoord3sv"`
  TexCoord4d func(...any) (any, error) `v8:"texCoord4d"`
  TexCoord4dv func(...any) (any, error) `v8:"texCoord4dv"`
  TexCoord4f func(...any) (any, error) `v8:"texCoord4f"`
  TexCoord4fv func(...any) (any, error) `v8:"texCoord4fv"`
  TexCoord4i func(...any) (any, error) `v8:"texCoord4i"`
  TexCoord4iv func(...any) (any, error) `v8:"texCoord4iv"`
  TexCoord4s func(...any) (any, error) `v8:"texCoord4s"`
  TexCoord4sv func(...any) (any, error) `v8:"texCoord4sv"`
  TexCoordPointer func(...any) (any, error) `v8:"texCoordPointer"`
  TexEnvf func(...any) (any, error) `v8:"texEnvf"`
  TexEnvfv func(...any) (any, error) `v8:"texEnvfv"`
  TexEnvi func(...any) (any, error) `v8:"texEnvi"`
  TexEnviv func(...any) (any, error) `v8:"texEnviv"`
  TexGend func(...any) (any, error) `v8:"texGend"`
  TexGendv func(...any) (any, error) `v8:"texGendv"`
  TexGenf func(...any) (any, error) `v8:"texGenf"`
  TexGenfv func(...any) (any, error) `v8:"texGenfv"`
  TexGeni func(...any) (any, error) `v8:"texGeni"`
  TexGeniv func(...any) (any, error) `v8:"texGeniv"`
  TexImage1D func(...any) (any, error) `v8:"texImage1D"`
  TexImage2D func(...any) (any, error) `v8:"texImage2D"`
  TexParameterf func(...any) (any, error) `v8:"texParameterf"`
  TexParameterfv func(...any) (any, error) `v8:"texParameterfv"`
  TexParameteri func(...any) (any, error) `v8:"texParameteri"`
  TexParameteriv func(...any) (any, error) `v8:"texParameteriv"`
  TexSubImage1D func(...any) (any, error) `v8:"texSubImage1D"`
  TexSubImage2D func(...any) (any, error) `v8:"texSubImage2D"`
  Translated func(...any) (any, error) `v8:"translated"`
  Translatef func(...any) (any, error) `v8:"translatef"`
  Vertex2d func(...any) (any, error) `v8:"vertex2d"`
  Vertex2dv func(...any) (any, error) `v8:"vertex2dv"`
  Vertex2f func(...any) (any, error) `v8:"vertex2f"`
  Vertex2fv func(...any) (any, error) `v8:"vertex2fv"`
  Vertex2i func(...any) (any, error) `v8:"vertex2i"`
  Vertex2iv func(...any) (any, error) `v8:"vertex2iv"`
  Vertex2s func(...any) (any, error) `v8:"vertex2s"`
  Vertex2sv func(...any) (any, error) `v8:"vertex2sv"`
  Vertex3d func(...any) (any, error) `v8:"vertex3d"`
  Vertex3dv func(...any) (any, error) `v8:"vertex3dv"`
  Vertex3f func(...any) (any, error) `v8:"vertex3f"`
  Vertex3fv func(...any) (any, error) `v8:"vertex3fv"`
  Vertex3i func(...any) (any, error) `v8:"vertex3i"`
  Vertex3iv func(...any) (any, error) `v8:"vertex3iv"`
  Vertex3s func(...any) (any, error) `v8:"vertex3s"`
  Vertex3sv func(...any) (any, error) `v8:"vertex3sv"`
  Vertex4d func(...any) (any, error) `v8:"vertex4d"`
  Vertex4dv func(...any) (any, error) `v8:"vertex4dv"`
  Vertex4f func(...any) (any, error) `v8:"vertex4f"`
  Vertex4fv func(...any) (any, error) `v8:"vertex4fv"`
  Vertex4i func(...any) (any, error) `v8:"vertex4i"`
  Vertex4iv func(...any) (any, error) `v8:"vertex4iv"`
  Vertex4s func(...any) (any, error) `v8:"vertex4s"`
  Vertex4sv func(...any) (any, error) `v8:"vertex4sv"`
  VertexPointer func(...any) (any, error) `v8:"vertexPointer"`
  Viewport func(...any) (any, error) `v8:"viewport"`
  BlendFuncSeparate func(...any) (any, error) `v8:"blendFuncSeparate"`
  BlendColor func(...any) (any, error) `v8:"blendColor"`
  BlendEquation func(...any) (any, error) `v8:"blendEquation"`
  LockArraysEXT func(...any) (any, error) `v8:"lockArraysEXT"`
  UnlockArraysEXT func(...any) (any, error) `v8:"unlockArraysEXT"`
  ClientActiveTexture func(...any) (any, error) `v8:"clientActiveTexture"`
  ActiveTexture func(...any) (any, error) `v8:"activeTexture"`
  MultiTexCoord1d func(...any) (any, error) `v8:"multiTexCoord1d"`
  MultiTexCoord1dv func(...any) (any, error) `v8:"multiTexCoord1dv"`
  MultiTexCoord1f func(...any) (any, error) `v8:"multiTexCoord1f"`
  MultiTexCoord1fv func(...any) (any, error) `v8:"multiTexCoord1fv"`
  MultiTexCoord1i func(...any) (any, error) `v8:"multiTexCoord1i"`
  MultiTexCoord1iv func(...any) (any, error) `v8:"multiTexCoord1iv"`
  MultiTexCoord1s func(...any) (any, error) `v8:"multiTexCoord1s"`
  MultiTexCoord1sv func(...any) (any, error) `v8:"multiTexCoord1sv"`
  MultiTexCoord2d func(...any) (any, error) `v8:"multiTexCoord2d"`
  MultiTexCoord2dv func(...any) (any, error) `v8:"multiTexCoord2dv"`
  MultiTexCoord2f func(...any) (any, error) `v8:"multiTexCoord2f"`
  MultiTexCoord2fv func(...any) (any, error) `v8:"multiTexCoord2fv"`
  MultiTexCoord2i func(...any) (any, error) `v8:"multiTexCoord2i"`
  MultiTexCoord2iv func(...any) (any, error) `v8:"multiTexCoord2iv"`
  MultiTexCoord2s func(...any) (any, error) `v8:"multiTexCoord2s"`
  MultiTexCoord2sv func(...any) (any, error) `v8:"multiTexCoord2sv"`
  MultiTexCoord3d func(...any) (any, error) `v8:"multiTexCoord3d"`
  MultiTexCoord3dv func(...any) (any, error) `v8:"multiTexCoord3dv"`
  MultiTexCoord3f func(...any) (any, error) `v8:"multiTexCoord3f"`
  MultiTexCoord3fv func(...any) (any, error) `v8:"multiTexCoord3fv"`
  MultiTexCoord3i func(...any) (any, error) `v8:"multiTexCoord3i"`
  MultiTexCoord3iv func(...any) (any, error) `v8:"multiTexCoord3iv"`
  MultiTexCoord3s func(...any) (any, error) `v8:"multiTexCoord3s"`
  MultiTexCoord3sv func(...any) (any, error) `v8:"multiTexCoord3sv"`
  MultiTexCoord4d func(...any) (any, error) `v8:"multiTexCoord4d"`
  MultiTexCoord4dv func(...any) (any, error) `v8:"multiTexCoord4dv"`
  MultiTexCoord4f func(...any) (any, error) `v8:"multiTexCoord4f"`
  MultiTexCoord4fv func(...any) (any, error) `v8:"multiTexCoord4fv"`
  MultiTexCoord4i func(...any) (any, error) `v8:"multiTexCoord4i"`
  MultiTexCoord4iv func(...any) (any, error) `v8:"multiTexCoord4iv"`
  MultiTexCoord4s func(...any) (any, error) `v8:"multiTexCoord4s"`
  MultiTexCoord4sv func(...any) (any, error) `v8:"multiTexCoord4sv"`
  LoadTransposeMatrixd func(...any) (any, error) `v8:"loadTransposeMatrixd"`
  LoadTransposeMatrixf func(...any) (any, error) `v8:"loadTransposeMatrixf"`
  MultTransposeMatrixd func(...any) (any, error) `v8:"multTransposeMatrixd"`
  MultTransposeMatrixf func(...any) (any, error) `v8:"multTransposeMatrixf"`
  CompressedTexImage3D func(...any) (any, error) `v8:"compressedTexImage3D"`
  CompressedTexImage2D func(...any) (any, error) `v8:"compressedTexImage2D"`
  CompressedTexImage1D func(...any) (any, error) `v8:"compressedTexImage1D"`
  CompressedTexSubImage3D func(...any) (any, error) `v8:"compressedTexSubImage3D"`
  CompressedTexSubImage2D func(...any) (any, error) `v8:"compressedTexSubImage2D"`
  CompressedTexSubImage1D func(...any) (any, error) `v8:"compressedTexSubImage1D"`
  GetCompressedTexImage func(...any) (any, error) `v8:"getCompressedTexImage"`
  SecondaryColor3b func(...any) (any, error) `v8:"secondaryColor3b"`
  SecondaryColor3bv func(...any) (any, error) `v8:"secondaryColor3bv"`
  SecondaryColor3d func(...any) (any, error) `v8:"secondaryColor3d"`
  SecondaryColor3dv func(...any) (any, error) `v8:"secondaryColor3dv"`
  SecondaryColor3f func(...any) (any, error) `v8:"secondaryColor3f"`
  SecondaryColor3fv func(...any) (any, error) `v8:"secondaryColor3fv"`
  SecondaryColor3i func(...any) (any, error) `v8:"secondaryColor3i"`
  SecondaryColor3iv func(...any) (any, error) `v8:"secondaryColor3iv"`
  SecondaryColor3s func(...any) (any, error) `v8:"secondaryColor3s"`
  SecondaryColor3sv func(...any) (any, error) `v8:"secondaryColor3sv"`
  SecondaryColor3ub func(...any) (any, error) `v8:"secondaryColor3ub"`
  SecondaryColor3ubv func(...any) (any, error) `v8:"secondaryColor3ubv"`
  SecondaryColor3ui func(...any) (any, error) `v8:"secondaryColor3ui"`
  SecondaryColor3uiv func(...any) (any, error) `v8:"secondaryColor3uiv"`
  SecondaryColor3us func(...any) (any, error) `v8:"secondaryColor3us"`
  SecondaryColor3usv func(...any) (any, error) `v8:"secondaryColor3usv"`
  SecondaryColorPointer func(...any) (any, error) `v8:"secondaryColorPointer"`
  VertexArrayRangeEXT func(...any) (any, error) `v8:"vertexArrayRangeEXT"`
  FlushVertexArrayRangeEXT func(...any) (any, error) `v8:"flushVertexArrayRangeEXT"`
  DrawRangeElements func(...any) (any, error) `v8:"drawRangeElements"`
  ColorTable func(...any) (any, error) `v8:"colorTable"`
  ColorTableParameterfv func(...any) (any, error) `v8:"colorTableParameterfv"`
  ColorTableParameteriv func(...any) (any, error) `v8:"colorTableParameteriv"`
  CopyColorTable func(...any) (any, error) `v8:"copyColorTable"`
  GetColorTable func(...any) (any, error) `v8:"getColorTable"`
  GetColorTableParameterfv func(...any) (any, error) `v8:"getColorTableParameterfv"`
  GetColorTableParameteriv func(...any) (any, error) `v8:"getColorTableParameteriv"`
  ColorSubTable func(...any) (any, error) `v8:"colorSubTable"`
  CopyColorSubTable func(...any) (any, error) `v8:"copyColorSubTable"`
  ConvolutionFilter1D func(...any) (any, error) `v8:"convolutionFilter1D"`
  ConvolutionFilter2D func(...any) (any, error) `v8:"convolutionFilter2D"`
  ConvolutionParameterf func(...any) (any, error) `v8:"convolutionParameterf"`
  ConvolutionParameterfv func(...any) (any, error) `v8:"convolutionParameterfv"`
  ConvolutionParameteri func(...any) (any, error) `v8:"convolutionParameteri"`
  ConvolutionParameteriv func(...any) (any, error) `v8:"convolutionParameteriv"`
  CopyConvolutionFilter1D func(...any) (any, error) `v8:"copyConvolutionFilter1D"`
  CopyConvolutionFilter2D func(...any) (any, error) `v8:"copyConvolutionFilter2D"`
  GetConvolutionFilter func(...any) (any, error) `v8:"getConvolutionFilter"`
  GetConvolutionParameterfv func(...any) (any, error) `v8:"getConvolutionParameterfv"`
  GetConvolutionParameteriv func(...any) (any, error) `v8:"getConvolutionParameteriv"`
  GetSeparableFilter func(...any) (any, error) `v8:"getSeparableFilter"`
  SeparableFilter2D func(...any) (any, error) `v8:"separableFilter2D"`
  GetHistogram func(...any) (any, error) `v8:"getHistogram"`
  GetHistogramParameterfv func(...any) (any, error) `v8:"getHistogramParameterfv"`
  GetHistogramParameteriv func(...any) (any, error) `v8:"getHistogramParameteriv"`
  GetMinmax func(...any) (any, error) `v8:"getMinmax"`
  GetMinmaxParameterfv func(...any) (any, error) `v8:"getMinmaxParameterfv"`
  GetMinmaxParameteriv func(...any) (any, error) `v8:"getMinmaxParameteriv"`
  Histogram func(...any) (any, error) `v8:"histogram"`
  Minmax func(...any) (any, error) `v8:"minmax"`
  ResetHistogram func(...any) (any, error) `v8:"resetHistogram"`
  ResetMinmax func(...any) (any, error) `v8:"resetMinmax"`
  TexImage3D func(...any) (any, error) `v8:"texImage3D"`
  TexSubImage3D func(...any) (any, error) `v8:"texSubImage3D"`
  CopyTexSubImage3D func(...any) (any, error) `v8:"copyTexSubImage3D"`
  GetUniformIndices func(...any) (any, error) `v8:"getUniformIndices"`
  GetActiveUniformsiv func(...any) (any, error) `v8:"getActiveUniformsiv"`
  GetActiveUniformName func(...any) (any, error) `v8:"getActiveUniformName"`
  GetUniformBlockIndex func(...any) (any, error) `v8:"getUniformBlockIndex"`
  GetActiveUniformBlockiv func(...any) (any, error) `v8:"getActiveUniformBlockiv"`
  GetActiveUniformBlockName func(...any) (any, error) `v8:"getActiveUniformBlockName"`
  UniformBlockBinding func(...any) (any, error) `v8:"uniformBlockBinding"`
  GetCombinerInputParameterfvNV func(...any) (any, error) `v8:"getCombinerInputParameterfvNV"`
  GetCombinerInputParameterivNV func(...any) (any, error) `v8:"getCombinerInputParameterivNV"`
  GetCombinerOutputParameterfvNV func(...any) (any, error) `v8:"getCombinerOutputParameterfvNV"`
  GetCombinerOutputParameterivNV func(...any) (any, error) `v8:"getCombinerOutputParameterivNV"`
  GetFinalCombinerInputParameterfvNV func(...any) (any, error) `v8:"getFinalCombinerInputParameterfvNV"`
  GetFinalCombinerInputParameterivNV func(...any) (any, error) `v8:"getFinalCombinerInputParameterivNV"`
  CombinerStageParameterfvNV func(...any) (any, error) `v8:"combinerStageParameterfvNV"`
  GetCombinerStageParameterfvNV func(...any) (any, error) `v8:"getCombinerStageParameterfvNV"`
  TextureRangeAPPLE func(...any) (any, error) `v8:"textureRangeAPPLE"`
  GetTexParameterPointervAPPLE func(...any) (any, error) `v8:"getTexParameterPointervAPPLE"`
  BlendEquationSeparateEXT func(...any) (any, error) `v8:"blendEquationSeparateEXT"`
  SampleCoverage func(...any) (any, error) `v8:"sampleCoverage"`
  SamplePass func(...any) (any, error) `v8:"samplePass"`
  PnTrianglesiATI func(...any) (any, error) `v8:"pnTrianglesiATI"`
  PnTrianglesfATI func(...any) (any, error) `v8:"pnTrianglesfATI"`
  GenFencesAPPLE func(...any) (any, error) `v8:"genFencesAPPLE"`
  DeleteFencesAPPLE func(...any) (any, error) `v8:"deleteFencesAPPLE"`
  SetFenceAPPLE func(...any) (any, error) `v8:"setFenceAPPLE"`
  IsFenceAPPLE func(...any) (any, error) `v8:"isFenceAPPLE"`
  TestFenceAPPLE func(...any) (any, error) `v8:"testFenceAPPLE"`
  FinishFenceAPPLE func(...any) (any, error) `v8:"finishFenceAPPLE"`
  TestObjectAPPLE func(...any) (any, error) `v8:"testObjectAPPLE"`
  FinishObjectAPPLE func(...any) (any, error) `v8:"finishObjectAPPLE"`
  BindProgramARB func(...any) (any, error) `v8:"bindProgramARB"`
  DeleteProgramsARB func(...any) (any, error) `v8:"deleteProgramsARB"`
  GenProgramsARB func(...any) (any, error) `v8:"genProgramsARB"`
  IsProgramARB func(...any) (any, error) `v8:"isProgramARB"`
  VertexAttrib1sARB func(...any) (any, error) `v8:"vertexAttrib1sARB"`
  VertexAttrib1fARB func(...any) (any, error) `v8:"vertexAttrib1fARB"`
  VertexAttrib1dARB func(...any) (any, error) `v8:"vertexAttrib1dARB"`
  VertexAttrib2sARB func(...any) (any, error) `v8:"vertexAttrib2sARB"`
  VertexAttrib2fARB func(...any) (any, error) `v8:"vertexAttrib2fARB"`
  VertexAttrib2dARB func(...any) (any, error) `v8:"vertexAttrib2dARB"`
  VertexAttrib3sARB func(...any) (any, error) `v8:"vertexAttrib3sARB"`
  VertexAttrib3fARB func(...any) (any, error) `v8:"vertexAttrib3fARB"`
  VertexAttrib3dARB func(...any) (any, error) `v8:"vertexAttrib3dARB"`
  VertexAttrib4sARB func(...any) (any, error) `v8:"vertexAttrib4sARB"`
  VertexAttrib4fARB func(...any) (any, error) `v8:"vertexAttrib4fARB"`
  VertexAttrib4dARB func(...any) (any, error) `v8:"vertexAttrib4dARB"`
  VertexAttrib4NubARB func(...any) (any, error) `v8:"vertexAttrib4NubARB"`
  VertexAttrib1svARB func(...any) (any, error) `v8:"vertexAttrib1svARB"`
  VertexAttrib1fvARB func(...any) (any, error) `v8:"vertexAttrib1fvARB"`
  VertexAttrib1dvARB func(...any) (any, error) `v8:"vertexAttrib1dvARB"`
  VertexAttrib2svARB func(...any) (any, error) `v8:"vertexAttrib2svARB"`
  VertexAttrib2fvARB func(...any) (any, error) `v8:"vertexAttrib2fvARB"`
  VertexAttrib2dvARB func(...any) (any, error) `v8:"vertexAttrib2dvARB"`
  VertexAttrib3svARB func(...any) (any, error) `v8:"vertexAttrib3svARB"`
  VertexAttrib3fvARB func(...any) (any, error) `v8:"vertexAttrib3fvARB"`
  VertexAttrib3dvARB func(...any) (any, error) `v8:"vertexAttrib3dvARB"`
  VertexAttrib4bvARB func(...any) (any, error) `v8:"vertexAttrib4bvARB"`
  VertexAttrib4svARB func(...any) (any, error) `v8:"vertexAttrib4svARB"`
  VertexAttrib4ivARB func(...any) (any, error) `v8:"vertexAttrib4ivARB"`
  VertexAttrib4ubvARB func(...any) (any, error) `v8:"vertexAttrib4ubvARB"`
  VertexAttrib4usvARB func(...any) (any, error) `v8:"vertexAttrib4usvARB"`
  VertexAttrib4uivARB func(...any) (any, error) `v8:"vertexAttrib4uivARB"`
  VertexAttrib4fvARB func(...any) (any, error) `v8:"vertexAttrib4fvARB"`
  VertexAttrib4dvARB func(...any) (any, error) `v8:"vertexAttrib4dvARB"`
  VertexAttrib4NbvARB func(...any) (any, error) `v8:"vertexAttrib4NbvARB"`
  VertexAttrib4NsvARB func(...any) (any, error) `v8:"vertexAttrib4NsvARB"`
  VertexAttrib4NivARB func(...any) (any, error) `v8:"vertexAttrib4NivARB"`
  VertexAttrib4NubvARB func(...any) (any, error) `v8:"vertexAttrib4NubvARB"`
  VertexAttrib4NusvARB func(...any) (any, error) `v8:"vertexAttrib4NusvARB"`
  VertexAttrib4NuivARB func(...any) (any, error) `v8:"vertexAttrib4NuivARB"`
  VertexAttribPointerARB func(...any) (any, error) `v8:"vertexAttribPointerARB"`
  EnableVertexAttribArrayARB func(...any) (any, error) `v8:"enableVertexAttribArrayARB"`
  DisableVertexAttribArrayARB func(...any) (any, error) `v8:"disableVertexAttribArrayARB"`
  GetVertexAttribdvARB func(...any) (any, error) `v8:"getVertexAttribdvARB"`
  GetVertexAttribfvARB func(...any) (any, error) `v8:"getVertexAttribfvARB"`
  GetVertexAttribivARB func(...any) (any, error) `v8:"getVertexAttribivARB"`
  GetVertexAttribPointervARB func(...any) (any, error) `v8:"getVertexAttribPointervARB"`
  ProgramEnvParameter4dARB func(...any) (any, error) `v8:"programEnvParameter4dARB"`
  ProgramEnvParameter4dvARB func(...any) (any, error) `v8:"programEnvParameter4dvARB"`
  ProgramEnvParameter4fARB func(...any) (any, error) `v8:"programEnvParameter4fARB"`
  ProgramEnvParameter4fvARB func(...any) (any, error) `v8:"programEnvParameter4fvARB"`
  ProgramLocalParameter4dARB func(...any) (any, error) `v8:"programLocalParameter4dARB"`
  ProgramLocalParameter4dvARB func(...any) (any, error) `v8:"programLocalParameter4dvARB"`
  ProgramLocalParameter4fARB func(...any) (any, error) `v8:"programLocalParameter4fARB"`
  ProgramLocalParameter4fvARB func(...any) (any, error) `v8:"programLocalParameter4fvARB"`
  GetProgramEnvParameterdvARB func(...any) (any, error) `v8:"getProgramEnvParameterdvARB"`
  GetProgramEnvParameterfvARB func(...any) (any, error) `v8:"getProgramEnvParameterfvARB"`
  GetProgramLocalParameterdvARB func(...any) (any, error) `v8:"getProgramLocalParameterdvARB"`
  GetProgramLocalParameterfvARB func(...any) (any, error) `v8:"getProgramLocalParameterfvARB"`
  ProgramStringARB func(...any) (any, error) `v8:"programStringARB"`
  GetProgramStringARB func(...any) (any, error) `v8:"getProgramStringARB"`
  GetProgramivARB func(...any) (any, error) `v8:"getProgramivARB"`
  EnableVertexAttribARB func(...any) (any, error) `v8:"enableVertexAttribARB"`
  DisableVertexAttribARB func(...any) (any, error) `v8:"disableVertexAttribARB"`
  IsVertexAttribEnabledARB func(...any) (any, error) `v8:"isVertexAttribEnabledARB"`
  MapVertexAttrib1dARB func(...any) (any, error) `v8:"mapVertexAttrib1dARB"`
  MapVertexAttrib1fARB func(...any) (any, error) `v8:"mapVertexAttrib1fARB"`
  MapVertexAttrib2dARB func(...any) (any, error) `v8:"mapVertexAttrib2dARB"`
  MapVertexAttrib2fARB func(...any) (any, error) `v8:"mapVertexAttrib2fARB"`
  PointParameterf func(...any) (any, error) `v8:"pointParameterf"`
  PointParameterfv func(...any) (any, error) `v8:"pointParameterfv"`
  PointParameteri func(...any) (any, error) `v8:"pointParameteri"`
  PointParameteriv func(...any) (any, error) `v8:"pointParameteriv"`
  FogCoordf func(...any) (any, error) `v8:"fogCoordf"`
  FogCoordfv func(...any) (any, error) `v8:"fogCoordfv"`
  FogCoordd func(...any) (any, error) `v8:"fogCoordd"`
  FogCoorddv func(...any) (any, error) `v8:"fogCoorddv"`
  FogCoordPointer func(...any) (any, error) `v8:"fogCoordPointer"`
  VertexArrayParameteriEXT func(...any) (any, error) `v8:"vertexArrayParameteriEXT"`
  BindVertexArrayEXT func(...any) (any, error) `v8:"bindVertexArrayEXT"`
  DeleteVertexArraysEXT func(...any) (any, error) `v8:"deleteVertexArraysEXT"`
  GenVertexArraysEXT func(...any) (any, error) `v8:"genVertexArraysEXT"`
  IsVertexArrayEXT func(...any) (any, error) `v8:"isVertexArrayEXT"`
  ElementPointerAPPLE func(...any) (any, error) `v8:"elementPointerAPPLE"`
  DrawElementArrayAPPLE func(...any) (any, error) `v8:"drawElementArrayAPPLE"`
  DrawRangeElementArrayAPPLE func(...any) (any, error) `v8:"drawRangeElementArrayAPPLE"`
  WeightbvARB func(...any) (any, error) `v8:"weightbvARB"`
  WeightsvARB func(...any) (any, error) `v8:"weightsvARB"`
  WeightivARB func(...any) (any, error) `v8:"weightivARB"`
  WeightfvARB func(...any) (any, error) `v8:"weightfvARB"`
  WeightdvARB func(...any) (any, error) `v8:"weightdvARB"`
  WeightubvARB func(...any) (any, error) `v8:"weightubvARB"`
  WeightusvARB func(...any) (any, error) `v8:"weightusvARB"`
  WeightuivARB func(...any) (any, error) `v8:"weightuivARB"`
  WeightPointerARB func(...any) (any, error) `v8:"weightPointerARB"`
  VertexBlendARB func(...any) (any, error) `v8:"vertexBlendARB"`
  MultiDrawArrays func(...any) (any, error) `v8:"multiDrawArrays"`
  MultiDrawElements func(...any) (any, error) `v8:"multiDrawElements"`
  WindowPos2d func(...any) (any, error) `v8:"windowPos2d"`
  WindowPos2dv func(...any) (any, error) `v8:"windowPos2dv"`
  WindowPos2f func(...any) (any, error) `v8:"windowPos2f"`
  WindowPos2fv func(...any) (any, error) `v8:"windowPos2fv"`
  WindowPos2i func(...any) (any, error) `v8:"windowPos2i"`
  WindowPos2iv func(...any) (any, error) `v8:"windowPos2iv"`
  WindowPos2s func(...any) (any, error) `v8:"windowPos2s"`
  WindowPos2sv func(...any) (any, error) `v8:"windowPos2sv"`
  WindowPos3d func(...any) (any, error) `v8:"windowPos3d"`
  WindowPos3dv func(...any) (any, error) `v8:"windowPos3dv"`
  WindowPos3f func(...any) (any, error) `v8:"windowPos3f"`
  WindowPos3fv func(...any) (any, error) `v8:"windowPos3fv"`
  WindowPos3i func(...any) (any, error) `v8:"windowPos3i"`
  WindowPos3iv func(...any) (any, error) `v8:"windowPos3iv"`
  WindowPos3s func(...any) (any, error) `v8:"windowPos3s"`
  WindowPos3sv func(...any) (any, error) `v8:"windowPos3sv"`
  ActiveStencilFaceEXT func(...any) (any, error) `v8:"activeStencilFaceEXT"`
  StencilOpSeparateATI func(...any) (any, error) `v8:"stencilOpSeparateATI"`
  StencilFuncSeparateATI func(...any) (any, error) `v8:"stencilFuncSeparateATI"`
  FlushRenderAPPLE func(...any) (any, error) `v8:"flushRenderAPPLE"`
  FinishRenderAPPLE func(...any) (any, error) `v8:"finishRenderAPPLE"`
  SwapAPPLE func(...any) (any, error) `v8:"swapAPPLE"`
  DeleteObjectARB func(...any) (any, error) `v8:"deleteObjectARB"`
  GetHandleARB func(...any) (any, error) `v8:"getHandleARB"`
  DetachObjectARB func(...any) (any, error) `v8:"detachObjectARB"`
  CreateShaderObjectARB func(...any) (any, error) `v8:"createShaderObjectARB"`
  ShaderSourceARB func(...any) (any, error) `v8:"shaderSourceARB"`
  CompileShaderARB func(...any) (any, error) `v8:"compileShaderARB"`
  CreateProgramObjectARB func(...any) (any, error) `v8:"createProgramObjectARB"`
  AttachObjectARB func(...any) (any, error) `v8:"attachObjectARB"`
  LinkProgramARB func(...any) (any, error) `v8:"linkProgramARB"`
  UseProgramObjectARB func(...any) (any, error) `v8:"useProgramObjectARB"`
  ValidateProgramARB func(...any) (any, error) `v8:"validateProgramARB"`
  Uniform1fARB func(...any) (any, error) `v8:"uniform1fARB"`
  Uniform2fARB func(...any) (any, error) `v8:"uniform2fARB"`
  Uniform3fARB func(...any) (any, error) `v8:"uniform3fARB"`
  Uniform4fARB func(...any) (any, error) `v8:"uniform4fARB"`
  Uniform1iARB func(...any) (any, error) `v8:"uniform1iARB"`
  Uniform2iARB func(...any) (any, error) `v8:"uniform2iARB"`
  Uniform3iARB func(...any) (any, error) `v8:"uniform3iARB"`
  Uniform4iARB func(...any) (any, error) `v8:"uniform4iARB"`
  Uniform1fvARB func(...any) (any, error) `v8:"uniform1fvARB"`
  Uniform2fvARB func(...any) (any, error) `v8:"uniform2fvARB"`
  Uniform3fvARB func(...any) (any, error) `v8:"uniform3fvARB"`
  Uniform4fvARB func(...any) (any, error) `v8:"uniform4fvARB"`
  Uniform1ivARB func(...any) (any, error) `v8:"uniform1ivARB"`
  Uniform2ivARB func(...any) (any, error) `v8:"uniform2ivARB"`
  Uniform3ivARB func(...any) (any, error) `v8:"uniform3ivARB"`
  Uniform4ivARB func(...any) (any, error) `v8:"uniform4ivARB"`
  UniformMatrix2fvARB func(...any) (any, error) `v8:"uniformMatrix2fvARB"`
  UniformMatrix3fvARB func(...any) (any, error) `v8:"uniformMatrix3fvARB"`
  UniformMatrix4fvARB func(...any) (any, error) `v8:"uniformMatrix4fvARB"`
  GetObjectParameterfvARB func(...any) (any, error) `v8:"getObjectParameterfvARB"`
  GetObjectParameterivARB func(...any) (any, error) `v8:"getObjectParameterivARB"`
  GetInfoLogARB func(...any) (any, error) `v8:"getInfoLogARB"`
  GetAttachedObjectsARB func(...any) (any, error) `v8:"getAttachedObjectsARB"`
  GetUniformLocationARB func(...any) (any, error) `v8:"getUniformLocationARB"`
  GetActiveUniformARB func(...any) (any, error) `v8:"getActiveUniformARB"`
  GetUniformfvARB func(...any) (any, error) `v8:"getUniformfvARB"`
  GetUniformivARB func(...any) (any, error) `v8:"getUniformivARB"`
  GetShaderSourceARB func(...any) (any, error) `v8:"getShaderSourceARB"`
  BindAttribLocationARB func(...any) (any, error) `v8:"bindAttribLocationARB"`
  GetActiveAttribARB func(...any) (any, error) `v8:"getActiveAttribARB"`
  GetAttribLocationARB func(...any) (any, error) `v8:"getAttribLocationARB"`
  ClampColorARB func(...any) (any, error) `v8:"clampColorARB"`
  GenQueries func(...any) (any, error) `v8:"genQueries"`
  DeleteQueries func(...any) (any, error) `v8:"deleteQueries"`
  IsQuery func(...any) (any, error) `v8:"isQuery"`
  BeginQuery func(...any) (any, error) `v8:"beginQuery"`
  EndQuery func(...any) (any, error) `v8:"endQuery"`
  GetQueryiv func(...any) (any, error) `v8:"getQueryiv"`
  GetQueryObjectiv func(...any) (any, error) `v8:"getQueryObjectiv"`
  GetQueryObjectuiv func(...any) (any, error) `v8:"getQueryObjectuiv"`
  BindBuffer func(...any) (any, error) `v8:"bindBuffer"`
  DeleteBuffers func(...any) (any, error) `v8:"deleteBuffers"`
  GenBuffers func(...any) (any, error) `v8:"genBuffers"`
  IsBuffer func(...any) (any, error) `v8:"isBuffer"`
  BufferData func(...any) (any, error) `v8:"bufferData"`
  BufferSubData func(...any) (any, error) `v8:"bufferSubData"`
  GetBufferSubData func(...any) (any, error) `v8:"getBufferSubData"`
  MapBuffer func(...any) (any, error) `v8:"mapBuffer"`
  UnmapBuffer func(...any) (any, error) `v8:"unmapBuffer"`
  GetBufferParameteriv func(...any) (any, error) `v8:"getBufferParameteriv"`
  GetBufferPointerv func(...any) (any, error) `v8:"getBufferPointerv"`
  DepthBoundsEXT func(...any) (any, error) `v8:"depthBoundsEXT"`
  DrawBuffersARB func(...any) (any, error) `v8:"drawBuffersARB"`
  IsShader func(...any) (any, error) `v8:"isShader"`
  IsProgram func(...any) (any, error) `v8:"isProgram"`
  GetShaderiv func(...any) (any, error) `v8:"getShaderiv"`
  GetProgramiv func(...any) (any, error) `v8:"getProgramiv"`
  GetShaderInfoLog func(...any) (any, error) `v8:"getShaderInfoLog"`
  GetProgramInfoLog func(...any) (any, error) `v8:"getProgramInfoLog"`
  StencilFuncSeparate func(...any) (any, error) `v8:"stencilFuncSeparate"`
  StencilMaskSeparate func(...any) (any, error) `v8:"stencilMaskSeparate"`
  MultiDrawElementArrayAPPLE func(...any) (any, error) `v8:"multiDrawElementArrayAPPLE"`
  MultiDrawRangeElementArrayAPPLE func(...any) (any, error) `v8:"multiDrawRangeElementArrayAPPLE"`
  IsRenderbufferEXT func(...any) (any, error) `v8:"isRenderbufferEXT"`
  BindRenderbufferEXT func(...any) (any, error) `v8:"bindRenderbufferEXT"`
  DeleteRenderbuffersEXT func(...any) (any, error) `v8:"deleteRenderbuffersEXT"`
  GenRenderbuffersEXT func(...any) (any, error) `v8:"genRenderbuffersEXT"`
  RenderbufferStorageEXT func(...any) (any, error) `v8:"renderbufferStorageEXT"`
  GetRenderbufferParameterivEXT func(...any) (any, error) `v8:"getRenderbufferParameterivEXT"`
  IsFramebufferEXT func(...any) (any, error) `v8:"isFramebufferEXT"`
  BindFramebufferEXT func(...any) (any, error) `v8:"bindFramebufferEXT"`
  DeleteFramebuffersEXT func(...any) (any, error) `v8:"deleteFramebuffersEXT"`
  GenFramebuffersEXT func(...any) (any, error) `v8:"genFramebuffersEXT"`
  CheckFramebufferStatusEXT func(...any) (any, error) `v8:"checkFramebufferStatusEXT"`
  FramebufferTexture1DEXT func(...any) (any, error) `v8:"framebufferTexture1DEXT"`
  FramebufferTexture2DEXT func(...any) (any, error) `v8:"framebufferTexture2DEXT"`
  FramebufferTexture3DEXT func(...any) (any, error) `v8:"framebufferTexture3DEXT"`
  FramebufferRenderbufferEXT func(...any) (any, error) `v8:"framebufferRenderbufferEXT"`
  GetFramebufferAttachmentParameterivEXT func(...any) (any, error) `v8:"getFramebufferAttachmentParameterivEXT"`
  GenerateMipmapEXT func(...any) (any, error) `v8:"generateMipmapEXT"`
  BufferParameteriAPPLE func(...any) (any, error) `v8:"bufferParameteriAPPLE"`
  FlushMappedBufferRangeAPPLE func(...any) (any, error) `v8:"flushMappedBufferRangeAPPLE"`
  ProgramEnvParameters4fvEXT func(...any) (any, error) `v8:"programEnvParameters4fvEXT"`
  ProgramLocalParameters4fvEXT func(...any) (any, error) `v8:"programLocalParameters4fvEXT"`
  ObjectPurgeableAPPLE func(...any) (any, error) `v8:"objectPurgeableAPPLE"`
  ObjectUnpurgeableAPPLE func(...any) (any, error) `v8:"objectUnpurgeableAPPLE"`
  GetObjectParameterivAPPLE func(...any) (any, error) `v8:"getObjectParameterivAPPLE"`
  ProgramParameteriEXT func(...any) (any, error) `v8:"programParameteriEXT"`
  FramebufferTextureEXT func(...any) (any, error) `v8:"framebufferTextureEXT"`
  FramebufferTextureLayerEXT func(...any) (any, error) `v8:"framebufferTextureLayerEXT"`
  FramebufferTextureFaceEXT func(...any) (any, error) `v8:"framebufferTextureFaceEXT"`
  BindBufferRangeEXT func(...any) (any, error) `v8:"bindBufferRangeEXT"`
  BindBufferOffsetEXT func(...any) (any, error) `v8:"bindBufferOffsetEXT"`
  BindBufferBaseEXT func(...any) (any, error) `v8:"bindBufferBaseEXT"`
  BeginTransformFeedbackEXT func(...any) (any, error) `v8:"beginTransformFeedbackEXT"`
  EndTransformFeedbackEXT func(...any) (any, error) `v8:"endTransformFeedbackEXT"`
  TransformFeedbackVaryingsEXT func(...any) (any, error) `v8:"transformFeedbackVaryingsEXT"`
  GetTransformFeedbackVaryingEXT func(...any) (any, error) `v8:"getTransformFeedbackVaryingEXT"`
  GetIntegerIndexedvEXT func(...any) (any, error) `v8:"getIntegerIndexedvEXT"`
  GetBooleanIndexedvEXT func(...any) (any, error) `v8:"getBooleanIndexedvEXT"`
  UniformBufferEXT func(...any) (any, error) `v8:"uniformBufferEXT"`
  GetUniformBufferSizeEXT func(...any) (any, error) `v8:"getUniformBufferSizeEXT"`
  GetUniformBufferOffsetEXT func(...any) (any, error) `v8:"getUniformBufferOffsetEXT"`
  ClearColorIiEXT func(...any) (any, error) `v8:"clearColorIiEXT"`
  ClearColorIuiEXT func(...any) (any, error) `v8:"clearColorIuiEXT"`
  TexParameterIivEXT func(...any) (any, error) `v8:"texParameterIivEXT"`
  TexParameterIuivEXT func(...any) (any, error) `v8:"texParameterIuivEXT"`
  GetTexParameterIivEXT func(...any) (any, error) `v8:"getTexParameterIivEXT"`
  GetTexParameterIuivEXT func(...any) (any, error) `v8:"getTexParameterIuivEXT"`
  VertexAttribI1iEXT func(...any) (any, error) `v8:"vertexAttribI1iEXT"`
  VertexAttribI2iEXT func(...any) (any, error) `v8:"vertexAttribI2iEXT"`
  VertexAttribI3iEXT func(...any) (any, error) `v8:"vertexAttribI3iEXT"`
  VertexAttribI4iEXT func(...any) (any, error) `v8:"vertexAttribI4iEXT"`
  VertexAttribI1uiEXT func(...any) (any, error) `v8:"vertexAttribI1uiEXT"`
  VertexAttribI2uiEXT func(...any) (any, error) `v8:"vertexAttribI2uiEXT"`
  VertexAttribI3uiEXT func(...any) (any, error) `v8:"vertexAttribI3uiEXT"`
  VertexAttribI4uiEXT func(...any) (any, error) `v8:"vertexAttribI4uiEXT"`
  VertexAttribI1ivEXT func(...any) (any, error) `v8:"vertexAttribI1ivEXT"`
  VertexAttribI2ivEXT func(...any) (any, error) `v8:"vertexAttribI2ivEXT"`
  VertexAttribI3ivEXT func(...any) (any, error) `v8:"vertexAttribI3ivEXT"`
  VertexAttribI4ivEXT func(...any) (any, error) `v8:"vertexAttribI4ivEXT"`
  VertexAttribI1uivEXT func(...any) (any, error) `v8:"vertexAttribI1uivEXT"`
  VertexAttribI2uivEXT func(...any) (any, error) `v8:"vertexAttribI2uivEXT"`
  VertexAttribI3uivEXT func(...any) (any, error) `v8:"vertexAttribI3uivEXT"`
  VertexAttribI4uivEXT func(...any) (any, error) `v8:"vertexAttribI4uivEXT"`
  VertexAttribI4bvEXT func(...any) (any, error) `v8:"vertexAttribI4bvEXT"`
  VertexAttribI4svEXT func(...any) (any, error) `v8:"vertexAttribI4svEXT"`
  VertexAttribI4ubvEXT func(...any) (any, error) `v8:"vertexAttribI4ubvEXT"`
  VertexAttribI4usvEXT func(...any) (any, error) `v8:"vertexAttribI4usvEXT"`
  VertexAttribIPointerEXT func(...any) (any, error) `v8:"vertexAttribIPointerEXT"`
  GetVertexAttribIivEXT func(...any) (any, error) `v8:"getVertexAttribIivEXT"`
  GetVertexAttribIuivEXT func(...any) (any, error) `v8:"getVertexAttribIuivEXT"`
  Uniform1uiEXT func(...any) (any, error) `v8:"uniform1uiEXT"`
  Uniform2uiEXT func(...any) (any, error) `v8:"uniform2uiEXT"`
  Uniform3uiEXT func(...any) (any, error) `v8:"uniform3uiEXT"`
  Uniform4uiEXT func(...any) (any, error) `v8:"uniform4uiEXT"`
  Uniform1uivEXT func(...any) (any, error) `v8:"uniform1uivEXT"`
  Uniform2uivEXT func(...any) (any, error) `v8:"uniform2uivEXT"`
  Uniform3uivEXT func(...any) (any, error) `v8:"uniform3uivEXT"`
  Uniform4uivEXT func(...any) (any, error) `v8:"uniform4uivEXT"`
  GetUniformuivEXT func(...any) (any, error) `v8:"getUniformuivEXT"`
  BindFragDataLocationEXT func(...any) (any, error) `v8:"bindFragDataLocationEXT"`
  GetFragDataLocationEXT func(...any) (any, error) `v8:"getFragDataLocationEXT"`
  ColorMaskIndexedEXT func(...any) (any, error) `v8:"colorMaskIndexedEXT"`
  EnableIndexedEXT func(...any) (any, error) `v8:"enableIndexedEXT"`
  DisableIndexedEXT func(...any) (any, error) `v8:"disableIndexedEXT"`
  IsEnabledIndexedEXT func(...any) (any, error) `v8:"isEnabledIndexedEXT"`
  UniformMatrix2x3fv func(...any) (any, error) `v8:"uniformMatrix2x3fv"`
  UniformMatrix3x2fv func(...any) (any, error) `v8:"uniformMatrix3x2fv"`
  UniformMatrix2x4fv func(...any) (any, error) `v8:"uniformMatrix2x4fv"`
  UniformMatrix4x2fv func(...any) (any, error) `v8:"uniformMatrix4x2fv"`
  UniformMatrix3x4fv func(...any) (any, error) `v8:"uniformMatrix3x4fv"`
  UniformMatrix4x3fv func(...any) (any, error) `v8:"uniformMatrix4x3fv"`
  BlitFramebufferEXT func(...any) (any, error) `v8:"blitFramebufferEXT"`
  RenderbufferStorageMultisampleEXT func(...any) (any, error) `v8:"renderbufferStorageMultisampleEXT"`
  BeginConditionalRenderNV func(...any) (any, error) `v8:"beginConditionalRenderNV"`
  EndConditionalRenderNV func(...any) (any, error) `v8:"endConditionalRenderNV"`
  GetAttachedShaders func(...any) (any, error) `v8:"getAttachedShaders"`
  ProvokingVertexEXT func(...any) (any, error) `v8:"provokingVertexEXT"`
  VertexAttribDivisor func(...any) (any, error) `v8:"vertexAttribDivisor"`
  DrawArraysInstanced func(...any) (any, error) `v8:"drawArraysInstanced"`
  DrawElementsInstanced func(...any) (any, error) `v8:"drawElementsInstanced"`
  DrawElementsBaseVertex func(...any) (any, error) `v8:"drawElementsBaseVertex"`
  DrawRangeElementsBaseVertex func(...any) (any, error) `v8:"drawRangeElementsBaseVertex"`
  DrawElementsInstancedBaseVertex func(...any) (any, error) `v8:"drawElementsInstancedBaseVertex"`
  MultiDrawElementsBaseVertex func(...any) (any, error) `v8:"multiDrawElementsBaseVertex"`
  BindVertexArrayARB func(...any) (any, error) `v8:"bindVertexArrayARB"`
  DeleteVertexArraysARB func(...any) (any, error) `v8:"deleteVertexArraysARB"`
  GenVertexArraysARB func(...any) (any, error) `v8:"genVertexArraysARB"`
  IsVertexArrayARB func(...any) (any, error) `v8:"isVertexArrayARB"`
  PointSizePointer func(...any) (any, error) `v8:"pointSizePointer"`
  VertexPointSizefAPPLE func(...any) (any, error) `v8:"vertexPointSizefAPPLE"`
  ClearBufferiv func(...any) (any, error) `v8:"clearBufferiv"`
  ClearBufferuiv func(...any) (any, error) `v8:"clearBufferuiv"`
  ClearBufferfv func(...any) (any, error) `v8:"clearBufferfv"`
  ClearBufferfi func(...any) (any, error) `v8:"clearBufferfi"`
  GetStringi func(...any) (any, error) `v8:"getStringi"`
  FenceSync func(...any) (any, error) `v8:"fenceSync"`
  IsSync func(...any) (any, error) `v8:"isSync"`
  DeleteSync func(...any) (any, error) `v8:"deleteSync"`
  ClientWaitSync func(...any) (any, error) `v8:"clientWaitSync"`
  WaitSync func(...any) (any, error) `v8:"waitSync"`
  GetInteger64vSync func(...any) (any, error) `v8:"getInteger64vSync"`
  GetSynciv func(...any) (any, error) `v8:"getSynciv"`
  TexImage2DMultisample func(...any) (any, error) `v8:"texImage2DMultisample"`
  TexImage3DMultisample func(...any) (any, error) `v8:"texImage3DMultisample"`
  GetMultisamplefv func(...any) (any, error) `v8:"getMultisamplefv"`
  SampleMaski func(...any) (any, error) `v8:"sampleMaski"`
  TexBuffer func(...any) (any, error) `v8:"texBuffer"`
  CopyBufferSubData func(...any) (any, error) `v8:"copyBufferSubData"`
  PrimitiveRestartIndex func(...any) (any, error) `v8:"primitiveRestartIndex"`
  GetQueryObjecti64v func(...any) (any, error) `v8:"getQueryObjecti64v"`
  GetQueryObjectui64v func(...any) (any, error) `v8:"getQueryObjectui64v"`
  MapBufferRange func(...any) (any, error) `v8:"mapBufferRange"`
  FlushMappedBufferRange func(...any) (any, error) `v8:"flushMappedBufferRange"`
  QueryCounter func(...any) (any, error) `v8:"queryCounter"`
  GetInteger64iV func(...any) (any, error) `v8:"getInteger64iV"`
  GetBufferParameteri64v func(...any) (any, error) `v8:"getBufferParameteri64v"`
  GenSamplers func(...any) (any, error) `v8:"genSamplers"`
  DeleteSamplers func(...any) (any, error) `v8:"deleteSamplers"`
  IsSampler func(...any) (any, error) `v8:"isSampler"`
  BindSampler func(...any) (any, error) `v8:"bindSampler"`
  SamplerParameteri func(...any) (any, error) `v8:"samplerParameteri"`
  SamplerParameteriv func(...any) (any, error) `v8:"samplerParameteriv"`
  SamplerParameterf func(...any) (any, error) `v8:"samplerParameterf"`
  SamplerParameterfv func(...any) (any, error) `v8:"samplerParameterfv"`
  SamplerParameterIiv func(...any) (any, error) `v8:"samplerParameterIiv"`
  SamplerParameterIuiv func(...any) (any, error) `v8:"samplerParameterIuiv"`
  GetSamplerParameteriv func(...any) (any, error) `v8:"getSamplerParameteriv"`
  GetSamplerParameterfv func(...any) (any, error) `v8:"getSamplerParameterfv"`
  GetSamplerParameterIiv func(...any) (any, error) `v8:"getSamplerParameterIiv"`
  GetSamplerParameterIuiv func(...any) (any, error) `v8:"getSamplerParameterIuiv"`
  LabelObjectEXT func(...any) (any, error) `v8:"labelObjectEXT"`
  GetObjectLabelEXT func(...any) (any, error) `v8:"getObjectLabelEXT"`
  InsertEventMarkerEXT func(...any) (any, error) `v8:"insertEventMarkerEXT"`
  PushGroupMarkerEXT func(...any) (any, error) `v8:"pushGroupMarkerEXT"`
  PopGroupMarkerEXT func(...any) (any, error) `v8:"popGroupMarkerEXT"`
  UseProgramStages func(...any) (any, error) `v8:"useProgramStages"`
  ActiveShaderProgram func(...any) (any, error) `v8:"activeShaderProgram"`
  CreateShaderProgramv func(...any) (any, error) `v8:"createShaderProgramv"`
  BindProgramPipeline func(...any) (any, error) `v8:"bindProgramPipeline"`
  DeleteProgramPipelines func(...any) (any, error) `v8:"deleteProgramPipelines"`
  GenProgramPipelines func(...any) (any, error) `v8:"genProgramPipelines"`
  IsProgramPipeline func(...any) (any, error) `v8:"isProgramPipeline"`
  GetProgramPipelineiv func(...any) (any, error) `v8:"getProgramPipelineiv"`
  ValidateProgramPipeline func(...any) (any, error) `v8:"validateProgramPipeline"`
  GetProgramPipelineInfoLog func(...any) (any, error) `v8:"getProgramPipelineInfoLog"`
  ProgramUniform1i func(...any) (any, error) `v8:"programUniform1i"`
  ProgramUniform2i func(...any) (any, error) `v8:"programUniform2i"`
  ProgramUniform3i func(...any) (any, error) `v8:"programUniform3i"`
  ProgramUniform4i func(...any) (any, error) `v8:"programUniform4i"`
  ProgramUniform1f func(...any) (any, error) `v8:"programUniform1f"`
  ProgramUniform2f func(...any) (any, error) `v8:"programUniform2f"`
  ProgramUniform3f func(...any) (any, error) `v8:"programUniform3f"`
  ProgramUniform4f func(...any) (any, error) `v8:"programUniform4f"`
  ProgramUniform1iv func(...any) (any, error) `v8:"programUniform1iv"`
  ProgramUniform2iv func(...any) (any, error) `v8:"programUniform2iv"`
  ProgramUniform3iv func(...any) (any, error) `v8:"programUniform3iv"`
  ProgramUniform4iv func(...any) (any, error) `v8:"programUniform4iv"`
  ProgramUniform1fv func(...any) (any, error) `v8:"programUniform1fv"`
  ProgramUniform2fv func(...any) (any, error) `v8:"programUniform2fv"`
  ProgramUniform3fv func(...any) (any, error) `v8:"programUniform3fv"`
  ProgramUniform4fv func(...any) (any, error) `v8:"programUniform4fv"`
  ProgramUniformMatrix2fv func(...any) (any, error) `v8:"programUniformMatrix2fv"`
  ProgramUniformMatrix3fv func(...any) (any, error) `v8:"programUniformMatrix3fv"`
  ProgramUniformMatrix4fv func(...any) (any, error) `v8:"programUniformMatrix4fv"`
  ProgramUniform1ui func(...any) (any, error) `v8:"programUniform1ui"`
  ProgramUniform2ui func(...any) (any, error) `v8:"programUniform2ui"`
  ProgramUniform3ui func(...any) (any, error) `v8:"programUniform3ui"`
  ProgramUniform4ui func(...any) (any, error) `v8:"programUniform4ui"`
  ProgramUniform1uiv func(...any) (any, error) `v8:"programUniform1uiv"`
  ProgramUniform2uiv func(...any) (any, error) `v8:"programUniform2uiv"`
  ProgramUniform3uiv func(...any) (any, error) `v8:"programUniform3uiv"`
  ProgramUniform4uiv func(...any) (any, error) `v8:"programUniform4uiv"`
  ProgramUniformMatrix2x3fv func(...any) (any, error) `v8:"programUniformMatrix2x3fv"`
  ProgramUniformMatrix3x2fv func(...any) (any, error) `v8:"programUniformMatrix3x2fv"`
  ProgramUniformMatrix2x4fv func(...any) (any, error) `v8:"programUniformMatrix2x4fv"`
  ProgramUniformMatrix4x2fv func(...any) (any, error) `v8:"programUniformMatrix4x2fv"`
  ProgramUniformMatrix3x4fv func(...any) (any, error) `v8:"programUniformMatrix3x4fv"`
  ProgramUniformMatrix4x3fv func(...any) (any, error) `v8:"programUniformMatrix4x3fv"`
  BindFragDataLocationIndexed func(...any) (any, error) `v8:"bindFragDataLocationIndexed"`
  GetFragDataIndex func(...any) (any, error) `v8:"getFragDataIndex"`
  BlendFuncI func(...any) (any, error) `v8:"blendFuncI"`
  BlendFuncSeparateI func(...any) (any, error) `v8:"blendFuncSeparateI"`
  BlendEquationI func(...any) (any, error) `v8:"blendEquationI"`
  BlendEquationSeparateI func(...any) (any, error) `v8:"blendEquationSeparateI"`
  NamedStringARB func(...any) (any, error) `v8:"namedStringARB"`
  DeleteNamedStringARB func(...any) (any, error) `v8:"deleteNamedStringARB"`
  CompileShaderIncludeARB func(...any) (any, error) `v8:"compileShaderIncludeARB"`
  IsNamedStringARB func(...any) (any, error) `v8:"isNamedStringARB"`
  GetNamedStringARB func(...any) (any, error) `v8:"getNamedStringARB"`
  GetNamedStringIvARB func(...any) (any, error) `v8:"getNamedStringIvARB"`
  ReleaseShaderCompiler func(...any) (any, error) `v8:"releaseShaderCompiler"`
  ShaderBinary func(...any) (any, error) `v8:"shaderBinary"`
  GetShaderPrecisionFormat func(...any) (any, error) `v8:"getShaderPrecisionFormat"`
  DepthRangef func(...any) (any, error) `v8:"depthRangef"`
  ClearDepthf func(...any) (any, error) `v8:"clearDepthf"`
  VertexAttribP1ui func(...any) (any, error) `v8:"vertexAttribP1ui"`
  VertexAttribP2ui func(...any) (any, error) `v8:"vertexAttribP2ui"`
  VertexAttribP3ui func(...any) (any, error) `v8:"vertexAttribP3ui"`
  VertexAttribP4ui func(...any) (any, error) `v8:"vertexAttribP4ui"`
  VertexAttribP1uiv func(...any) (any, error) `v8:"vertexAttribP1uiv"`
  VertexAttribP2uiv func(...any) (any, error) `v8:"vertexAttribP2uiv"`
  VertexAttribP3uiv func(...any) (any, error) `v8:"vertexAttribP3uiv"`
  VertexAttribP4uiv func(...any) (any, error) `v8:"vertexAttribP4uiv"`
  GetProgramBinary func(...any) (any, error) `v8:"getProgramBinary"`
  ProgramBinary func(...any) (any, error) `v8:"programBinary"`
  MinSampleShading func(...any) (any, error) `v8:"minSampleShading"`
  ViewportArrayv func(...any) (any, error) `v8:"viewportArrayv"`
  ViewportIndexedf func(...any) (any, error) `v8:"viewportIndexedf"`
  ViewportIndexedfv func(...any) (any, error) `v8:"viewportIndexedfv"`
  ScissorArrayv func(...any) (any, error) `v8:"scissorArrayv"`
  ScissorIndexed func(...any) (any, error) `v8:"scissorIndexed"`
  ScissorIndexedv func(...any) (any, error) `v8:"scissorIndexedv"`
  DepthRangeArrayv func(...any) (any, error) `v8:"depthRangeArrayv"`
  DepthRangeIndexed func(...any) (any, error) `v8:"depthRangeIndexed"`
  GetFloatiV func(...any) (any, error) `v8:"getFloatiV"`
  GetDoubleiV func(...any) (any, error) `v8:"getDoubleiV"`
  DrawArraysIndirect func(...any) (any, error) `v8:"drawArraysIndirect"`
  DrawElementsIndirect func(...any) (any, error) `v8:"drawElementsIndirect"`
  PatchParameteri func(...any) (any, error) `v8:"patchParameteri"`
  PatchParameterfv func(...any) (any, error) `v8:"patchParameterfv"`
  BindTransformFeedback func(...any) (any, error) `v8:"bindTransformFeedback"`
  GenTransformFeedbacks func(...any) (any, error) `v8:"genTransformFeedbacks"`
  DeleteTransformFeedbacks func(...any) (any, error) `v8:"deleteTransformFeedbacks"`
  PauseTransformFeedback func(...any) (any, error) `v8:"pauseTransformFeedback"`
  ResumeTransformFeedback func(...any) (any, error) `v8:"resumeTransformFeedback"`
  IsTransformFeedback func(...any) (any, error) `v8:"isTransformFeedback"`
  DrawTransformFeedback func(...any) (any, error) `v8:"drawTransformFeedback"`
  BeginQueryIndexed func(...any) (any, error) `v8:"beginQueryIndexed"`
  EndQueryIndexed func(...any) (any, error) `v8:"endQueryIndexed"`
  GetQueryIndexediv func(...any) (any, error) `v8:"getQueryIndexediv"`
  DrawTransformFeedbackStream func(...any) (any, error) `v8:"drawTransformFeedbackStream"`
  ProgramUniform1d func(...any) (any, error) `v8:"programUniform1d"`
  ProgramUniform2d func(...any) (any, error) `v8:"programUniform2d"`
  ProgramUniform3d func(...any) (any, error) `v8:"programUniform3d"`
  ProgramUniform4d func(...any) (any, error) `v8:"programUniform4d"`
  ProgramUniform1dv func(...any) (any, error) `v8:"programUniform1dv"`
  ProgramUniform2dv func(...any) (any, error) `v8:"programUniform2dv"`
  ProgramUniform3dv func(...any) (any, error) `v8:"programUniform3dv"`
  ProgramUniform4dv func(...any) (any, error) `v8:"programUniform4dv"`
  ProgramUniformMatrix2dv func(...any) (any, error) `v8:"programUniformMatrix2dv"`
  ProgramUniformMatrix3dv func(...any) (any, error) `v8:"programUniformMatrix3dv"`
  ProgramUniformMatrix4dv func(...any) (any, error) `v8:"programUniformMatrix4dv"`
  ProgramUniformMatrix2x3dv func(...any) (any, error) `v8:"programUniformMatrix2x3dv"`
  ProgramUniformMatrix3x2dv func(...any) (any, error) `v8:"programUniformMatrix3x2dv"`
  ProgramUniformMatrix2x4dv func(...any) (any, error) `v8:"programUniformMatrix2x4dv"`
  ProgramUniformMatrix4x2dv func(...any) (any, error) `v8:"programUniformMatrix4x2dv"`
  ProgramUniformMatrix3x4dv func(...any) (any, error) `v8:"programUniformMatrix3x4dv"`
  ProgramUniformMatrix4x3dv func(...any) (any, error) `v8:"programUniformMatrix4x3dv"`
  Uniform1d func(...any) (any, error) `v8:"uniform1d"`
  Uniform2d func(...any) (any, error) `v8:"uniform2d"`
  Uniform3d func(...any) (any, error) `v8:"uniform3d"`
  Uniform4d func(...any) (any, error) `v8:"uniform4d"`
  Uniform1dv func(...any) (any, error) `v8:"uniform1dv"`
  Uniform2dv func(...any) (any, error) `v8:"uniform2dv"`
  Uniform3dv func(...any) (any, error) `v8:"uniform3dv"`
  Uniform4dv func(...any) (any, error) `v8:"uniform4dv"`
  UniformMatrix2dv func(...any) (any, error) `v8:"uniformMatrix2dv"`
  UniformMatrix3dv func(...any) (any, error) `v8:"uniformMatrix3dv"`
  UniformMatrix4dv func(...any) (any, error) `v8:"uniformMatrix4dv"`
  UniformMatrix2x3dv func(...any) (any, error) `v8:"uniformMatrix2x3dv"`
  UniformMatrix3x2dv func(...any) (any, error) `v8:"uniformMatrix3x2dv"`
  UniformMatrix2x4dv func(...any) (any, error) `v8:"uniformMatrix2x4dv"`
  UniformMatrix4x2dv func(...any) (any, error) `v8:"uniformMatrix4x2dv"`
  UniformMatrix3x4dv func(...any) (any, error) `v8:"uniformMatrix3x4dv"`
  UniformMatrix4x3dv func(...any) (any, error) `v8:"uniformMatrix4x3dv"`
  GetUniformdv func(...any) (any, error) `v8:"getUniformdv"`
  VertexAttribl1d func(...any) (any, error) `v8:"vertexAttribl1d"`
  VertexAttribl2d func(...any) (any, error) `v8:"vertexAttribl2d"`
  VertexAttribl3d func(...any) (any, error) `v8:"vertexAttribl3d"`
  VertexAttribl4d func(...any) (any, error) `v8:"vertexAttribl4d"`
  VertexAttribl1dv func(...any) (any, error) `v8:"vertexAttribl1dv"`
  VertexAttribl2dv func(...any) (any, error) `v8:"vertexAttribl2dv"`
  VertexAttribl3dv func(...any) (any, error) `v8:"vertexAttribl3dv"`
  VertexAttribl4dv func(...any) (any, error) `v8:"vertexAttribl4dv"`
  VertexAttribLpointer func(...any) (any, error) `v8:"vertexAttribLpointer"`
  GetVertexAttribLdv func(...any) (any, error) `v8:"getVertexAttribLdv"`
  GetSubroutineUniformLocation func(...any) (any, error) `v8:"getSubroutineUniformLocation"`
  GetSubroutineIndex func(...any) (any, error) `v8:"getSubroutineIndex"`
  GetActiveSubroutineUniformiv func(...any) (any, error) `v8:"getActiveSubroutineUniformiv"`
  GetActiveSubroutineUniformName func(...any) (any, error) `v8:"getActiveSubroutineUniformName"`
  GetActiveSubroutineName func(...any) (any, error) `v8:"getActiveSubroutineName"`
  UniformSubroutinesuiv func(...any) (any, error) `v8:"uniformSubroutinesuiv"`
  GetUniformSubroutineuiv func(...any) (any, error) `v8:"getUniformSubroutineuiv"`
  GetProgramStageiv func(...any) (any, error) `v8:"getProgramStageiv"`
  GetInternalFormativ func(...any) (any, error) `v8:"getInternalFormativ"`
  TexStorage1D func(...any) (any, error) `v8:"texStorage1D"`
  TexStorage2D func(...any) (any, error) `v8:"texStorage2D"`
  TexStorage3D func(...any) (any, error) `v8:"texStorage3D"`
  LabelObjectWithResponsibleProcessAPPLE func(...any) (any, error) `v8:"labelObjectWithResponsibleProcessAPPLE"`
  TextureBarrierNV func(...any) (any, error) `v8:"textureBarrierNV"`
  MultiDrawElementsIndirectAPPLE func(...any) (any, error) `v8:"multiDrawElementsIndirectAPPLE"`
}
