// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package net

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("net", "address.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  if _, err := in.Context.CreateWithName(in.ExecutionContext, "SocketAddress", func (in isolates.FunctionArgs) (*Address, error) {
    return NewAddress(in)
  }); err != nil {
    return nil, err
  }

  return nil, nil
})

func (a *Address) V8GetFamily(in isolates.GetterArgs) (*isolates.Value, error) {
  result := a.Family()
  return in.Context.Create(in.ExecutionContext, result)
}

func (a *Address) V8GetAddress(in isolates.GetterArgs) (*isolates.Value, error) {
  result := a.Address()
  return in.Context.Create(in.ExecutionContext, result)
}

func (a *Address) V8GetPort(in isolates.GetterArgs) (*isolates.Value, error) {
  result := a.Port()
  return in.Context.Create(in.ExecutionContext, result)
}