// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package net

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("net", "net.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  if constructor, err := in.Context.CreateWithName(in.ExecutionContext, "Net", func (in isolates.FunctionArgs) (*NetBase, error) {
    return NewNet(in)
  }); err != nil {
    return nil, err
  } else if err := in.Args[1].Set(in.ExecutionContext, "Net", constructor); err != nil {
    return nil, err
  }

  return nil, nil
})

