// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package repl

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("repl", "/Users/tim/src/grexie/solid/pkg/runtime/repl/repl.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  return nil, nil
})

