// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package web

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("crypto/web", "library.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  {
    fnName := "getRandomValues"
    if fn, err := in.Context.CreateFunction(in.ExecutionContext, &fnName, func (in isolates.FunctionArgs) (*isolates.Value, error) {
  arrayBufferView := in.Arg(in.ExecutionContext, 0)
      if result, err := GetRandomValues(in.ExecutionContext, arrayBufferView); err != nil {
        return nil, err
      } else {
        return in.Context.Create(in.ExecutionContext, result)
      }
    }); err != nil {
      return nil, err
    } else if err := in.Args[1].Set(in.ExecutionContext, "getRandomValues", fn); err != nil {
      return nil, err
    }
  }

  {
    fnName := "createHmac"
    if fn, err := in.Context.CreateFunction(in.ExecutionContext, &fnName, func (in isolates.FunctionArgs) (*isolates.Value, error) {
      if result, err := CreateHmac(in.ExecutionContext); err != nil {
        return nil, err
      } else {
        return in.Context.Create(in.ExecutionContext, result)
      }
    }); err != nil {
      return nil, err
    } else if err := in.Args[1].Set(in.ExecutionContext, "createHmac", fn); err != nil {
      return nil, err
    }
  }

  return nil, nil
})

