// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package tty

import (
  reflect "reflect"
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("tty", "isatty.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  {
    fnName := "isatty"
    if fn, err := in.Context.CreateFunction(in.ExecutionContext, &fnName, func (in isolates.FunctionArgs) (*isolates.Value, error) {
  var fd int
      if v, __err := in.Arg(in.ExecutionContext, 0).Unmarshal(in.ExecutionContext, reflect.TypeOf(&fd).Elem()); __err != nil {
        return nil, __err
      } else {
        fd = v.Interface().(int)
      }

      if result, err := IsTTY(fd); err != nil {
        return nil, err
      } else {
        return in.Context.Create(in.ExecutionContext, result)
      }
    }); err != nil {
      return nil, err
    } else if err := in.Args[1].Set(in.ExecutionContext, "isatty", fn); err != nil {
      return nil, err
    }
  }

  return nil, nil
})

