// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package util

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("util", "/Users/tim/src/grexie/solid/pkg/runtime/util/deprecate.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  {
    fnName := "deprecate"
    if fn, err := in.Context.CreateFunction(in.ExecutionContext, &fnName, func (in isolates.FunctionArgs) (*isolates.Value, error) {
  fn := in.Arg(in.ExecutionContext, 0)
      msg := make([]*isolates.Value, len(in.Args)-1)
      for i, arg := range in.Args[1:] {
        msg[i] = arg
      }

      if result, err := Deprecate(fn, msg...); err != nil {
        return nil, err
      } else {
        return in.Context.Create(in.ExecutionContext, result)
      }
    }); err != nil {
      return nil, err
    } else if err := in.Args[1].Set(in.ExecutionContext, "deprecate", fn); err != nil {
      return nil, err
    }
  }

  return nil, nil
})

