// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package util

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("util", "promisify.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  {
    fnName := "promisify"
    if fn, err := in.Context.CreateFunction(in.ExecutionContext, &fnName, func (in isolates.FunctionArgs) (*isolates.Value, error) {
  fn := in.Arg(in.ExecutionContext, 0)
      if result, err := Promisify(in.ExecutionContext, fn); err != nil {
        return nil, err
      } else {
        return in.Context.Create(in.ExecutionContext, result)
      }
    }); err != nil {
      return nil, err
    } else if err := in.Args[1].Set(in.ExecutionContext, "promisify", fn); err != nil {
      return nil, err
    }
  }

  return nil, nil
})

