// this file is auto-generated by github.com/grexie/isolates, DO NOT EDIT

package http

import (
  isolates "github.com/grexie/isolates"
)

var _ = isolates.RegisterRuntime("http", "request.go", func (in isolates.FunctionArgs) (*isolates.Value, error) {
  return nil, nil
})

func (h *HttpBase) V8FuncRequest(in isolates.FunctionArgs) (*isolates.Value, error) {
  args := make([]any, len(in.Args)-0)
  for i, arg := range in.Args[0:] {
    args[i] = arg
  }

  if result, err := h.Request(in.ExecutionContext, args...); err != nil {
    return nil, err
  } else {
    return in.Context.Create(in.ExecutionContext, result)
  }
}